import type {
  AccessScope,
  AgentBackend,
  ContextSnapshot,
  CronJob,
  DirectoryBinding,
  ListResponse,
  McpBinding,
  McpServerConfig,
  Message,
  Project,
  ProjectArtifact,
  Secret,
  Task,
  TaskRunAttempt,
  ToolBinding,
} from "../types";

// Prefer a runtime-injected value (see public/runtime-config.js, generated by
// the Docker entrypoint from the VITE_API_URL container env var at startup)
// so the same build can point at different backends without rebuilding.
// Falls back to the build-time Vite env var, then localhost.
const BASE_URL =
  (typeof window !== "undefined" && window.__MUSTER_API_URL__) ||
  import.meta.env.VITE_API_URL ||
  "http://localhost:8080";

class ApiError extends Error {
  status: number;
  body: unknown;
  constructor(status: number, body: unknown) {
    super(`API error ${status}: ${JSON.stringify(body)}`);
    this.status = status;
    this.body = body;
  }
}

async function request<T>(
  path: string,
  options: RequestInit = {},
): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
  if (!res.ok) {
    let body: unknown = null;
    try {
      body = await res.json();
    } catch {
      // ignore body parse errors
    }
    throw new ApiError(res.status, body);
  }
  if (res.status === 204) {
    return undefined as T;
  }
  return (await res.json()) as T;
}

const get = <T>(path: string) => request<T>(path, { method: "GET" });
const post = <T>(path: string, body?: unknown) =>
  request<T>(path, { method: "POST", body: body ? JSON.stringify(body) : undefined });
const patch = <T>(path: string, body?: unknown) =>
  request<T>(path, { method: "PATCH", body: body ? JSON.stringify(body) : undefined });
const put = <T>(path: string, body?: unknown) =>
  request<T>(path, { method: "PUT", body: body ? JSON.stringify(body) : undefined });
const del = <T>(path: string) => request<T>(path, { method: "DELETE" });

// ---- Projects ----

export interface CreateProjectPayload {
  name: string;
  description?: string;
  default_backend: AgentBackend;
  default_model?: string;
  default_context_strategy?: string;
}

export const listProjects = (archived = false) =>
  get<ListResponse<Project>>(`/api/projects${archived ? "?archived=true" : ""}`);

export const createProject = (payload: CreateProjectPayload) =>
  post<Project>("/api/projects", payload);

export const getProject = (id: string) => get<Project>(`/api/projects/${id}`);

export const updateProject = (id: string, payload: Partial<CreateProjectPayload>) =>
  patch<Project>(`/api/projects/${id}`, payload);

export const archiveProject = (id: string) =>
  post<Project>(`/api/projects/${id}/archive`);

export const unarchiveProject = (id: string) =>
  post<Project>(`/api/projects/${id}/unarchive`);

// ---- Directories ----

export const listDirectories = (projectId: string) =>
  get<ListResponse<DirectoryBinding>>(`/api/projects/${projectId}/directories`);

export const createDirectory = (
  projectId: string,
  payload: { path: string; access_scope: AccessScope },
) => post<DirectoryBinding>(`/api/projects/${projectId}/directories`, payload);

export const deleteDirectory = (projectId: string, bindingId: string) =>
  del<void>(`/api/projects/${projectId}/directories/${bindingId}`);

// ---- MCP servers ----

export const listMcpServers = (projectId: string) =>
  get<ListResponse<McpBinding>>(`/api/projects/${projectId}/mcp-servers`);

export const createMcpServer = (
  projectId: string,
  payload: { name: string; config: McpServerConfig },
) => post<McpBinding>(`/api/projects/${projectId}/mcp-servers`, payload);

export const updateMcpServer = (
  projectId: string,
  bindingId: string,
  payload: Partial<{ name: string; config: McpServerConfig }>,
) => patch<McpBinding>(`/api/projects/${projectId}/mcp-servers/${bindingId}`, payload);

export const deleteMcpServer = (projectId: string, bindingId: string) =>
  del<void>(`/api/projects/${projectId}/mcp-servers/${bindingId}`);

// ---- Tools ----

export const listTools = (projectId: string) =>
  get<ListResponse<ToolBinding>>(`/api/projects/${projectId}/tools`);

export const createTool = (
  projectId: string,
  payload: { name: string; config: Record<string, unknown> },
) => post<ToolBinding>(`/api/projects/${projectId}/tools`, payload);

export const deleteTool = (projectId: string, bindingId: string) =>
  del<void>(`/api/projects/${projectId}/tools/${bindingId}`);

// ---- Artifacts ----

export const listArtifacts = (projectId: string) =>
  get<ListResponse<ProjectArtifact>>(`/api/projects/${projectId}/artifacts`);

export const createArtifact = (
  projectId: string,
  payload: { name: string; local_path: string; remote_url?: string },
) => post<ProjectArtifact>(`/api/projects/${projectId}/artifacts`, payload);

export const deleteArtifact = (projectId: string, artifactId: string) =>
  del<void>(`/api/projects/${projectId}/artifacts/${artifactId}`);

// ---- Secrets ----

export const listSecrets = (projectId: string) =>
  get<ListResponse<Secret>>(`/api/projects/${projectId}/secrets`);

export const upsertSecret = (projectId: string, keyName: string, value: string) =>
  put<Secret>(`/api/projects/${projectId}/secrets/${keyName}`, { value });

export const deleteSecret = (projectId: string, keyName: string) =>
  del<void>(`/api/projects/${projectId}/secrets/${keyName}`);

// ---- Cron jobs ----

export interface CreateCronJobPayload {
  name: string;
  schedule_expr: string;
  prompt: string;
  backend: AgentBackend;
  model?: string;
}

export const listCronJobs = (projectId: string) =>
  get<ListResponse<CronJob>>(`/api/projects/${projectId}/cron-jobs`);

export const createCronJob = (projectId: string, payload: CreateCronJobPayload) =>
  post<CronJob>(`/api/projects/${projectId}/cron-jobs`, payload);

export const updateCronJob = (
  projectId: string,
  cronId: string,
  payload: Partial<CreateCronJobPayload>,
) => patch<CronJob>(`/api/projects/${projectId}/cron-jobs/${cronId}`, payload);

export const enableCronJob = (projectId: string, cronId: string) =>
  post<CronJob>(`/api/projects/${projectId}/cron-jobs/${cronId}/enable`);

export const disableCronJob = (projectId: string, cronId: string) =>
  post<CronJob>(`/api/projects/${projectId}/cron-jobs/${cronId}/disable`);

export const deleteCronJob = (projectId: string, cronId: string) =>
  del<void>(`/api/projects/${projectId}/cron-jobs/${cronId}`);

// ---- Tasks ----

export interface CreateTaskPayload {
  title: string;
  initial_prompt: string;
  backend?: AgentBackend;
  model?: string;
  context_strategy?: string;
  media?: unknown[];
}

export const listTasks = (projectId: string, status?: string) =>
  get<ListResponse<Task>>(
    `/api/projects/${projectId}/tasks${status ? `?status=${status}` : ""}`,
  );

export const createTask = (projectId: string, payload: CreateTaskPayload) =>
  post<Task>(`/api/projects/${projectId}/tasks`, payload);

export const getTask = (id: string) => get<Task>(`/api/tasks/${id}`);

export const cancelTask = (id: string) => post<Task>(`/api/tasks/${id}/cancel`);

export const restartTask = (id: string) => post<Task>(`/api/tasks/${id}/restart`);

export const retryTaskNow = (id: string) => post<Task>(`/api/tasks/${id}/retry-now`);

export const switchTaskModel = (id: string, model: string) =>
  patch<Task>(`/api/tasks/${id}/model`, { model });

export const switchTaskContextStrategy = (id: string, context_strategy: string) =>
  patch<Task>(`/api/tasks/${id}/context-strategy`, { context_strategy });

export const compressTaskContext = (id: string) =>
  post<ContextSnapshot>(`/api/tasks/${id}/compress-context`);

// ---- Messages ----

export const listMessages = (taskId: string) =>
  get<ListResponse<Message>>(`/api/tasks/${taskId}/messages`);

export const sendMessage = (
  taskId: string,
  payload: { content_text?: string; media?: unknown[] },
) => post<Message>(`/api/tasks/${taskId}/messages`, payload);

export const getTranscript = async (taskId: string): Promise<string> => {
  const res = await fetch(`${BASE_URL}/api/tasks/${taskId}/transcript`, {
    method: "GET",
    headers: { Accept: "text/plain" },
  });
  if (!res.ok) {
    throw new ApiError(res.status, await res.text().catch(() => null));
  }
  return res.text();
};

// ---- Run attempts ----

export const listRunAttempts = (taskId: string) =>
  get<ListResponse<TaskRunAttempt>>(`/api/tasks/${taskId}/run-attempts`);

export { ApiError, BASE_URL };
