"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Bot, Code2, Download, FolderCode, Network, Pencil, Plus, RefreshCcw, ShieldCheck, Sparkles, Trash2 } from "lucide-react";
import { useState, type FormEvent } from "react";

import { Button } from "@/components/ui/button";
import { ImportCapabilitiesModal } from "@/components/registry/import-capabilities-modal";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/states";
import { useToast } from "@/components/ui/toast";
import { api } from "@/lib/api";
import type { AgentBackend, AgentProfile, DirectoryResource, GlobalMcpServer, GlobalTool, ListResponse, Skill, ToolRuleConfig } from "@/lib/types";
import { backendLabel, cn, formatRelativeTime } from "@/lib/utils";

type Kind = "agents" | "skills" | "tools" | "mcp" | "directories";
type Resource = AgentProfile | Skill | GlobalTool | GlobalMcpServer | DirectoryResource;

const meta = {
  agents: { title: "Agent profiles", description: "Reusable system prompts and execution defaults available to both runtimes.", singular: "agent", icon: Bot },
  skills: { title: "Skills library", description: "Instruction modules injected into enabled project sessions.", singular: "skill", icon: Sparkles },
  tools: { title: "Tool permissions", description: "Safe runtime capabilities inherited by every project, with project-level overrides.", singular: "tool", icon: Code2 },
  mcp: { title: "MCP connectors", description: "Global protocol servers enabled for every project unless explicitly disabled.", singular: "connector", icon: Network },
  directories: { title: "Directory registry", description: "Approved filesystem roots. Projects receive access through explicit bindings.", singular: "directory", icon: FolderCode },
};

export function RegistryManager({ kind }: { kind: Kind }) {
  const [editing, setEditing] = useState<Resource | null | "new">(null);
  const [importing, setImporting] = useState(false);
  const queryClient = useQueryClient(); const toast = useToast(); const details = meta[kind]; const Icon = details.icon;
  const query = useQuery<ListResponse<Resource>>({
    queryKey: ["registry", kind],
    queryFn: async () => {
      if (kind === "agents") return api.agents();
      if (kind === "skills") return api.skills();
      if (kind === "tools") return api.globalTools();
      if (kind === "mcp") return api.globalMcp();
      return api.globalDirectories();
    },
  });
  const remove = useMutation({ mutationFn: (id: string) => kind === "agents" ? api.deleteAgent(id) : kind === "skills" ? api.deleteSkill(id) : kind === "tools" ? api.deleteGlobalTool(id) : kind === "mcp" ? api.deleteGlobalMcp(id) : api.deleteGlobalDirectory(id), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["registry", kind] }); queryClient.invalidateQueries({ queryKey: ["capabilities"] }); toast(`${details.singular} deleted`, "success"); }, onError: (error: Error) => toast(error.message, "error") });
  return <div className="mx-auto max-w-6xl px-5 py-7 md:px-8 md:py-10">
    <div className="surface relative overflow-hidden rounded-panel px-6 py-7 md:px-8"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-signal-400/[0.05] blur-3xl" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-4 grid h-11 w-11 place-items-center rounded-xl border border-signal-400/15 bg-signal-400/[0.06] text-signal-400"><Icon className="h-5 w-5" /></div><p className="eyebrow">Global registry</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-white">{details.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{details.description}</p>{kind === "tools" && <div className="mt-4 inline-flex items-center gap-2 rounded-lg border border-signal-400/10 bg-signal-400/[0.035] px-3 py-2 text-[0.68rem] text-slate-400"><ShieldCheck className="h-3.5 w-3.5 text-signal-400" /> Codex commands remain constrained to the workspace-write sandbox.</div>}</div><div className="flex flex-wrap gap-2">{kind !== "directories" && kind !== "tools" && <Button onClick={() => setImporting(true)}><Download className="h-4 w-4" /> Import</Button>}<Button variant="primary" onClick={() => setEditing("new")}><Plus className="h-4 w-4" /> Add {details.singular}</Button></div></div></div>
    <div className="mt-5">
      {query.isPending && <div className="grid gap-3 md:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-40" />)}</div>}
      {query.isError && <ErrorState message={query.error.message} retry={() => query.refetch()} />}
      {query.isSuccess && query.data.items.length === 0 && <EmptyState title={`No ${details.title.toLowerCase()} yet`} description={`Add a ${details.singular} to make it available across Muster.`} action={<Button variant="primary" onClick={() => setEditing("new")}><Plus className="h-4 w-4" /> Add {details.singular}</Button>} />}
      {query.isSuccess && <div className="grid gap-3 md:grid-cols-2">{query.data.items.map((resource) => <RegistryCard key={resource.id} kind={kind} resource={resource} onEdit={() => setEditing(resource)} onDelete={() => remove.mutate(resource.id)} />)}</div>}
    </div>
    {editing && <RegistryForm key={editing === "new" ? "new" : editing.id} kind={kind} resource={editing === "new" ? null : editing} onClose={() => setEditing(null)} />}
    {kind !== "directories" && kind !== "tools" && <ImportCapabilitiesModal open={importing} onClose={() => setImporting(false)} initialKind={kind === "agents" ? "agent" : kind === "skills" ? "skill" : "mcp"} />}
  </div>;
}

function RegistryCard({ kind, resource, onEdit, onDelete }: { kind: Kind; resource: Resource; onEdit: () => void; onDelete: () => void }) {
  const [armed, setArmed] = useState(false); const Icon = meta[kind].icon; const enabled = "enabled" in resource ? resource.enabled : true;
  const tool = kind === "tools" ? resource as GlobalTool : null;
  const subtitle = kind === "directories" ? (resource as DirectoryResource).path : kind === "agents" ? `${backendLabel((resource as AgentProfile).backend)} · ${(resource as AgentProfile).model || "Runtime default"}` : kind === "tools" && tool ? `${tool.config.decision} · ${tool.config.backend === "all" ? "Claude + Codex" : backendLabel(tool.config.backend)}` : resource.description || "No description";
  return <motion.article layout whileHover={{ y: -2 }} className="surface flex min-h-36 flex-col rounded-panel p-5 transition-colors hover:border-white/[0.14]"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[0.08] bg-white/[0.03] text-signal-400"><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-sm font-medium text-white">{resource.name}</h2>{"enabled" in resource && <span className={cn("h-1.5 w-1.5 rounded-full", enabled ? "bg-signal-400" : "bg-slate-700")} />}</div><p className="mt-1 truncate text-xs text-slate-600">{subtitle}</p></div></div><div className="mt-auto flex items-end justify-between pt-5"><p className="font-mono text-[0.6rem] text-slate-700">Updated {formatRelativeTime(resource.updated_at)}</p><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={onEdit} aria-label={`Edit ${resource.name}`}><Pencil className="h-3.5 w-3.5" /></Button><Button size={armed ? "sm" : "icon"} variant={armed ? "danger" : "ghost"} onClick={() => armed ? onDelete() : setArmed(true)} onBlur={() => setArmed(false)} aria-label={armed ? `Confirm deletion of ${resource.name}` : `Delete ${resource.name}`}><Trash2 className="h-3.5 w-3.5" />{armed && "Confirm"}</Button></div></div></motion.article>;
}

function RegistryForm({ kind, resource, onClose }: { kind: Kind; resource: Resource | null; onClose: () => void }) {
  const queryClient = useQueryClient(); const toast = useToast(); const [error, setError] = useState("");
  const [name, setName] = useState(resource?.name ?? ""); const [description, setDescription] = useState(resource?.description ?? "");
  const [path, setPath] = useState(kind === "directories" && resource ? (resource as DirectoryResource).path : "");
  const agent = kind === "agents" ? resource as AgentProfile | null : null; const connector = kind === "mcp" ? resource as GlobalMcpServer | null : null; const skill = kind === "skills" ? resource as Skill | null : null; const tool = kind === "tools" ? resource as GlobalTool | null : null;
  const [backend, setBackend] = useState<AgentBackend>(agent?.backend ?? "claude_code"); const [systemPrompt, setSystemPrompt] = useState(agent?.system_prompt ?? ""); const [model, setModel] = useState(agent?.model ?? ""); const [thinking, setThinking] = useState(agent?.thinking_level ?? "medium"); const [enabled, setEnabled] = useState("enabled" in (resource ?? {}) ? Boolean((resource as AgentProfile).enabled) : true);
  const [instructions, setInstructions] = useState(skill?.instructions ?? ""); const [transport, setTransport] = useState<"stdio" | "http" | "sse">(connector?.config.transport ?? (connector?.config.url ? "http" : "stdio")); const [command, setCommand] = useState(connector?.config.command ?? ""); const [args, setArgs] = useState(connector?.config.args?.join(" ") ?? ""); const [env, setEnv] = useState(connector ? Object.entries(connector.config.env ?? {}).map(([key, value]) => `${key}=${value}`).join("\n") : ""); const [url, setUrl] = useState(connector?.config.url ?? ""); const [headers, setHeaders] = useState(connector ? Object.entries(connector.config.headers ?? {}).map(([key, value]) => `${key}=${value}`).join("\n") : ""); const [bearerTokenEnv, setBearerTokenEnv] = useState(connector?.config.bearer_token_env_var ?? "");
  const [toolBackend, setToolBackend] = useState<ToolRuleConfig["backend"]>(tool?.config.backend ?? "all"); const [decision, setDecision] = useState<ToolRuleConfig["decision"]>(tool?.config.decision ?? "allow"); const [claudePattern, setClaudePattern] = useState(tool?.config.claude_pattern ?? ""); const [codexPrefix, setCodexPrefix] = useState(tool?.config.codex_prefix.join(" ") ?? "");
  const models = useQuery({ queryKey: ["models", backend], queryFn: () => api.models(backend), enabled: kind === "agents", staleTime: 60 * 60 * 1000 });
  const refreshModels = useMutation({ mutationFn: () => api.models(backend, true), onSuccess: (catalog) => queryClient.setQueryData(["models", backend], catalog), onError: (cause: Error) => setError(cause.message) });
  const save = useMutation({ mutationFn: async () => {
    if (!name.trim()) throw new Error("Name is required.");
    if (kind === "directories") { if (!path.startsWith("/")) throw new Error("Use an absolute directory path."); const body = { name: name.trim(), path, description: description.trim() || null }; return resource ? api.updateGlobalDirectory(resource.id, body) : api.createGlobalDirectory(body); }
    if (kind === "skills") { if (!instructions.trim()) throw new Error("Skill instructions are required."); const body = { name: name.trim(), description: description.trim() || null, instructions, enabled }; return resource ? api.updateSkill(resource.id, body) : api.createSkill(body); }
    if (kind === "tools") { if (toolBackend !== "codex" && !claudePattern.trim()) throw new Error("A Claude tool pattern is required."); if (toolBackend !== "claude_code" && !codexPrefix.trim()) throw new Error("A Codex command prefix is required."); const config = { backend: toolBackend, decision, claude_pattern: toolBackend === "codex" ? null : claudePattern.trim(), codex_prefix: toolBackend === "claude_code" ? [] : codexPrefix.trim().split(/\s+/).filter(Boolean) }; const body = { name: name.trim(), description: description.trim() || null, config, enabled }; return resource ? api.updateGlobalTool(resource.id, body) : api.createGlobalTool(body); }
    if (kind === "mcp") { if (transport === "stdio" && !command.trim()) throw new Error("Connector command is required."); if (transport !== "stdio" && !url.trim()) throw new Error("Connector URL is required."); const parsePairs = (value: string) => Object.fromEntries(value.split("\n").filter(Boolean).map((line) => { const [key, ...rest] = line.split("="); return [key.trim(), rest.join("=").trim()]; })); const config = transport === "stdio" ? { transport, command: command.trim(), args: args.split(/\s+/).filter(Boolean), env: parsePairs(env), headers: {} } : { transport, command: null, args: [], env: {}, url: url.trim(), headers: parsePairs(headers), bearer_token_env_var: bearerTokenEnv.trim() || null }; const body = { name: name.trim(), description: description.trim() || null, enabled, config }; return resource ? api.updateGlobalMcp(resource.id, body) : api.createGlobalMcp(body); }
    if (!systemPrompt.trim()) throw new Error("Agent system prompt is required."); const body = { name: name.trim(), description: description.trim() || null, backend, system_prompt: systemPrompt, model: model || null, thinking_level: thinking, config: {}, enabled }; return resource ? api.updateAgent(resource.id, body) : api.createAgent(body);
  }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["registry", kind] }); queryClient.invalidateQueries({ queryKey: ["capabilities"] }); toast(`${meta[kind].singular} ${resource ? "updated" : "created"}`, "success"); onClose(); }, onError: (cause: Error) => setError(cause.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); setError(""); save.mutate(); };
  return <Modal open onClose={onClose} title={`${resource ? "Edit" : "Add"} ${meta[kind].singular}`} description="Changes become available to project sessions immediately." wide><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="registry-name">Name</label><input id="registry-name" className="field" value={name} onChange={(e) => setName(e.target.value)} autoFocus /></div>{kind === "directories" && <div><label className="label" htmlFor="registry-path">Absolute path</label><input id="registry-path" className="field font-mono" value={path} onChange={(e) => setPath(e.target.value)} /></div>}{kind === "agents" && <div><label className="label">Runtime</label><Select label="Select runtime" value={backend} onChange={(value) => { setBackend(value as AgentBackend); setModel(""); }} options={[{ value: "claude_code", label: "Claude Code" }, { value: "codex", label: "Codex" }]} /></div>}</div><div><label className="label" htmlFor="registry-description">Description</label><textarea id="registry-description" className="field min-h-20" value={description} onChange={(e) => setDescription(e.target.value)} /></div>
    {kind === "agents" && <><div><div className="mb-2 flex items-center justify-between"><label className="text-xs font-medium text-slate-300">Model</label><button type="button" onClick={() => refreshModels.mutate()} disabled={refreshModels.isPending} className="flex items-center gap-1 text-[0.65rem] text-signal-400 disabled:opacity-50"><RefreshCcw className={cn("h-3 w-3", refreshModels.isPending && "animate-spin")} /> Refresh from CLI</button></div><Select label={models.isPending ? "Discovering models" : "Select a model"} value={model} onChange={setModel} options={(models.data?.items ?? []).map((item) => ({ value: item.id, label: item.label, description: item.id }))} disabled={models.isPending} /></div><div><label className="label">Thinking level</label><Select label="Thinking level" value={thinking} onChange={setThinking} options={["low", "medium", "high", "xhigh", "max"].map((value) => ({ value, label: value[0].toUpperCase() + value.slice(1) }))} /></div><div><label className="label" htmlFor="agent-prompt">System prompt</label><textarea id="agent-prompt" className="field min-h-44 leading-6" value={systemPrompt} onChange={(e) => setSystemPrompt(e.target.value)} /></div></>}
    {kind === "skills" && <div><label className="label" htmlFor="skill-instructions">Instructions</label><textarea id="skill-instructions" className="field min-h-52 font-mono text-xs leading-6" value={instructions} onChange={(e) => setInstructions(e.target.value)} /></div>}
    {kind === "tools" && <><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Runtime</label><Select label="Select runtime" value={toolBackend} onChange={(value) => setToolBackend(value as ToolRuleConfig["backend"])} options={[{ value: "all", label: "Claude + Codex" }, { value: "claude_code", label: "Claude Code" }, { value: "codex", label: "Codex" }]} /></div><div><label className="label">Decision</label><Select label="Select decision" value={decision} onChange={(value) => setDecision(value as ToolRuleConfig["decision"])} options={[{ value: "allow", label: "Allow without asking" }, { value: "deny", label: "Always deny" }]} /></div></div>{toolBackend !== "codex" && <div><label className="label" htmlFor="global-tool-claude">Claude tool pattern</label><input id="global-tool-claude" className="field font-mono" value={claudePattern} onChange={(event) => setClaudePattern(event.target.value)} placeholder="Read or Bash(git status *)" /></div>}{toolBackend !== "claude_code" && <div><label className="label" htmlFor="global-tool-codex">Codex command prefix</label><input id="global-tool-codex" className="field font-mono" value={codexPrefix} onChange={(event) => setCodexPrefix(event.target.value)} placeholder="git status" /><p className="mt-2 text-[0.65rem] text-slate-600">Commands still run inside Codex&apos;s workspace-write sandbox.</p></div>}</>}
    {kind === "mcp" && <><div><label className="label">Transport</label><Select label="Select transport" value={transport} onChange={(value) => setTransport(value as "stdio" | "http" | "sse")} options={[{ value: "stdio", label: "Local process (stdio)" }, { value: "http", label: "Streamable HTTP" }, { value: "sse", label: "Server-sent events (SSE)" }]} /></div>{transport === "stdio" ? <><div><label className="label" htmlFor="mcp-command-global">Command</label><input id="mcp-command-global" className="field font-mono" value={command} onChange={(e) => setCommand(e.target.value)} /></div><div><label className="label" htmlFor="mcp-args-global">Arguments</label><input id="mcp-args-global" className="field font-mono" value={args} onChange={(e) => setArgs(e.target.value)} /></div><div><label className="label" htmlFor="mcp-env-global">Environment · one KEY=value per line</label><textarea id="mcp-env-global" className="field min-h-28 font-mono" value={env} onChange={(e) => setEnv(e.target.value)} /></div></> : <><div><label className="label" htmlFor="mcp-url-global">Server URL</label><input id="mcp-url-global" type="url" className="field font-mono" value={url} onChange={(e) => setUrl(e.target.value)} /></div><div><label className="label" htmlFor="mcp-headers-global">HTTP headers · one KEY=value per line</label><textarea id="mcp-headers-global" className="field min-h-24 font-mono" value={headers} onChange={(e) => setHeaders(e.target.value)} /></div><div><label className="label" htmlFor="mcp-bearer-global">Bearer-token environment variable</label><input id="mcp-bearer-global" className="field font-mono" placeholder="MCP_TOKEN" value={bearerTokenEnv} onChange={(e) => setBearerTokenEnv(e.target.value)} /></div></>}</>}
    {kind !== "directories" && <label className="flex cursor-pointer items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-3"><span><span className="block text-sm text-slate-200">Enabled globally</span><span className="mt-0.5 block text-[0.65rem] text-slate-600">Projects can override this setting.</span></span><button type="button" role="switch" aria-checked={enabled} onClick={() => setEnabled((value) => !value)} className={cn("relative h-6 w-11 rounded-full border transition", enabled ? "border-signal-400/30 bg-signal-400/20" : "border-white/10 bg-white/[0.04]")}><span className={cn("absolute top-1 h-3.5 w-3.5 rounded-full transition-all", enabled ? "left-6 bg-signal-400" : "left-1 bg-slate-600")} /></button></label>}
    {error && <p role="alert" className="rounded-xl border border-red-400/15 bg-red-400/[0.05] px-3 py-2.5 text-xs text-red-300">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" variant="primary" loading={save.isPending}>{resource ? "Save changes" : `Create ${meta[kind].singular}`}</Button></div></form></Modal>;
}
